apiVersion: v1
kind: Service
metadata:
  name: SUBSOCKER_APP_ENVIRONMENT-subsoccer-service
spec:
  selector:
    app: subsoccer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
